Task 1 - Data Loading & Exploration

In [1]:
import kagglehub

path = kagglehub.dataset_download("yasserh/housing-prices-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\pkuma\.cache\kagglehub\datasets\yasserh\housing-prices-dataset\versions\1

In [2]:
import pandas as pd
data = pd.read_csv(path + "/housing.csv")

In [3]:
data = pd.read_csv("D:\Project 1\Housing.csv")

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\pkuma\AppData\Local\Temp\ipykernel_24780\3624519260.py:1: SyntaxWarning: invalid escape sequence '\P'
  data = pd.read_csv("D:\Project 1\Housing.csv")

In [4]:
data.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [6]:
rows = pd.DataFrame(data).shape[0]
rows

545

In [7]:
columns = pd.DataFrame(data).shape[1]
columns

13

In [8]:
target = data['price']

In [9]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [10]:
data.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [11]:
data.duplicated().sum()

np.int64(0)

In [12]:
binary_columns = data.select_dtypes(include=['object']).columns.tolist()

In [13]:
binary_columns

['mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'prefarea',
 'furnishingstatus']

In [14]:
for i in binary_columns:
    data[i] = data[i].astype('category').cat.codes

In [15]:
data.dtypes

price               int64
area                int64
bedrooms            int64
bathrooms           int64
stories             int64
mainroad             int8
guestroom            int8
basement             int8
hotwaterheating      int8
airconditioning      int8
parking             int64
prefarea             int8
furnishingstatus     int8
dtype: object

In [16]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [17]:

from sklearn.preprocessing import StandardScaler as SS
from sklearn.model_selection import train_test_split as TTS
data = pd.get_dummies(data ,columns = ['furnishingstatus'], drop_first=True)
matrix = data.corr().abs()
matrix

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_1,furnishingstatus_2
price,1.000000,0.535997,0.366494,0.517545,0.420712,0.296898,0.255517,0.187057,0.093073,0.452954,0.384394,0.329777,0.063656,0.280587
area,0.535997,1.000000,0.151858,0.193820,0.083996,0.288874,0.140297,0.047417,0.009229,0.222393,0.352980,0.234779,0.006156,0.142278
bedrooms,0.366494,0.151858,1.000000,0.373930,0.408564,0.012033,0.080549,0.097312,0.046049,0.160603,0.139270,0.079023,0.050040,0.126252
bathrooms,0.517545,0.193820,0.373930,1.000000,0.326165,0.042398,0.126469,0.102106,0.067159,0.186915,0.177496,0.063472,0.029834,0.132107
stories,0.420712,0.083996,0.408564,0.326165,1.000000,0.121706,0.043538,0.172394,0.018847,0.293602,0.045547,0.044425,0.003648,0.082972
mainroad,0.296898,0.288874,0.012033,0.042398,0.121706,1.000000,0.092337,0.044002,0.011781,0.105423,0.204433,0.199876,0.011450,0.133123
guestroom,0.255517,0.140297,0.080549,0.126469,0.043538,0.092337,1.000000,0.372066,0.010308,0.138179,0.037466,0.160897,0.005821,0.099023
basement,0.187057,0.047417,0.097312,0.102106,0.172394,0.044002,0.372066,1.000000,0.004385,0.047341,0.051497,0.228083,0.050284,0.117935
hotwaterheating,0.093073,0.009229,0.046049,0.067159,0.018847,0.011781,0.010308,0.004385,1.000000,0.130023,0.067864,0.059411,0.063819,0.059194
airconditioning,0.452954,0.222393,0.160603,0.186915,0.293602,0.105423,0.138179,0.047341,0.130023,1.000000,0.159173,0.117382,0.053179,0.094086
parking,0.384394,0.352980,0.139270,0.177496,0.045547,0.204433,0.037466,0.051497,0.067864,0.159173,1.000000,0.091627,0.041327,0.165705
prefarea,0.329777,0.234779,0.079023,0.063472,0.044425,0.199876,0.160897,0.228083,0.059411,0.117382,0.091627,1.000000,0.011535,0.081271
furnishingstatus_1,0.063656,0.006156,0.050040,0.029834,0.003648,0.011450,0.005821,0.050284,0.063819,0.053179,0.041327,0.011535,1.000000,0.588405
furnishingstatus_2,0.280587,0.142278,0.126252,0.132107,0.082972,0.133123,0.099023,0.117935,0.059194,0.094086,0.165705,0.081271,0.588405,1.000000

In [18]:
df = data[['price','area', 'airconditioning','bathrooms','prefarea','parking']]
df

        price  area  airconditioning  bathrooms  prefarea  parking
0    13300000  7420                1          2         1        2
1    12250000  8960                1          4         0        3
2    12250000  9960                0          2         1        2
3    12215000  7500                1          2         1        3
4    11410000  7420                1          1         0        2
..        ...   ...              ...        ...       ...      ...
540   1820000  3000                0          1         0        2
541   1767150  2400                0          1         0        0
542   1750000  3620                0          1         0        0
543   1750000  2910                0          1         0        0
544   1750000  3850                0          1         0        0

[545 rows x 6 columns]

In [19]:
X_train, X_test, y_train, y_test = TTS(df.drop('price', axis=1), df['price'], test_size=0.2, random_state=42)

In [20]:
X_train.head(5)

     area  airconditioning  bathrooms  prefarea  parking
46   6000                1          2         0        1
93   7200                1          2         0        3
335  3816                1          1         0        2
412  2610                0          1         1        0
471  3750                0          1         0        0

In [ ]:
X_train = pd.DataFrame(SS.fit_transform(X_train), columns=X_train.columns)
X_test = pd.DataFrame(SS.fit_transform(X_test), columns=X_test.columns)

In [24]:
X_train.head(5)

       area  airconditioning  bathrooms  prefarea   parking
0  0.384168         1.501243   1.539173 -0.552620  0.367957
1  0.929181         1.501243   1.539173 -0.552620  2.709987
2 -0.607755         1.501243  -0.557950 -0.552620  1.538972
3 -1.155492        -0.666115  -0.557950  1.809561 -0.803059
4 -0.637730        -0.666115  -0.557950 -0.552620 -0.803059

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [29]:
lr.coef_

array([552052.54548485, 491258.76298738, 674740.70891348, 340167.28423076,
       220630.11851991])

In [ ]:
prediction = lr.predict(X_test)
prediction

array([5163103.35417603, 6906740.36387472, 3254901.77772196,
       4547130.15032133, 3233124.27407362, 3984448.14994148,
       6002857.85901225, 5464791.65369299, 3285885.51532042,
       2890128.5916122 , 9123588.84944363, 3226046.58538791,
       4198690.09194783, 2999016.10985392, 3235846.46202966,
       5449523.75662056, 2699575.43468919, 5068107.72000752,
       3996376.57184764, 3788450.61710639, 5350740.70383218,
       5842095.62989794, 3148464.22864068, 4236494.21845759,
       5147219.22946174, 7315236.61601014, 2996293.92189788,
       4124910.07284167, 8075008.00003912, 2971794.23029349,
       6226193.37486397, 3253219.2598479 , 5972464.78847381,
       3955865.17640303, 3454982.59249112, 5840117.24870968,
       3917383.91602195, 4051691.94232151, 4133357.5810028 ,
       4066927.46937796, 4824961.38056668, 4174190.40034344,
       6884962.86022638, 3547215.55910054, 3992614.71380961,
       5036802.55851303, 5972464.78847381, 3666991.82916643,
       4346499.1480952 , 3469311.77845728, 6871505.06015393,
       3220553.00437538, 4519036.65940789, 4411020.75251918,
       3146014.25948024, 2947294.53868911, 6951335.04125339,
       2808462.95293091, 3910949.07512832, 3189569.26677693,
       4671427.00421423, 3889440.81464396, 5685401.53823719,
       4536241.39849716, 4909914.31368218, 3676198.06311654,
       5903063.91461591, 2971794.23029349, 5188052.04880238,
       6033367.03300688, 4882243.43109979, 4684615.5611227 ,
       4690534.5006386 , 8244374.32037381, 4165430.19378367,
       4467905.75530309, 3640809.61968798, 5294935.8507333 ,
       5068107.72000752, 5426961.96660138, 7366147.2806539 ,
       3763308.07770992, 6101140.78761496, 4769003.38776003,
       2617909.79600791, 6332552.32446047, 2917350.47117263,
       3343051.46239732, 7654699.20399446, 6592199.85036653,
       2673714.64910679, 5626156.25099633, 3638730.27952403,
       4114302.2653105 , 7294524.34302562, 4193245.71603574,
       3741628.98426245, 5918021.02935295, 4699266.17098489,
       5903063.91461591, 3534644.28940231, 6088876.02279157,
       2963627.66642536, 5359691.55407114, 4285968.16527017,
       4290372.87110028, 6221223.5625557 , 6221223.5625557 ,
       6264472.06497754])

In [32]:
r2_score(y_test, prediction)

0.5400632814691368

In [33]:
mean_squared_error(y_test, prediction)

2324782452694.4326